### ISSUE TITLE
Restart processes on failure, or do better error handling

### ISSUE THREAD

**Issue by thewishy** [thewishy/clock#8]
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wishy/Clock/sensor_distance.py", line 81, in check_distance
    val = bus.read_byte_data(address, VL53L0X_REG_RESULT_RANGE_STATUS)
IOError: [Errno 121] Remote I/O error

**Comment by thewishy** [comment]
Error handling seems to be working nicely
